### ISSUE TITLE
[request] Raise error when services/apps are not defined

### ISSUE THREAD

**Issue by chadwcarlson** [Jeck-ai/upsunvalidator#15]
### Type

Feature request

### Proposal

```yaml
applications:
    drupal:
        type: "php:8.3"
        relationships:
            database: 'db:mysql'
            foo: 'bar:mysql'
            redis: 'cache:redis'
services:
    db:
        type: mariadb:10.6
    cache:
        type: redis:7.2
routes:
    "https://{default}/":
        type: upstream
        upstream: "drupalb:http"
    "https://www.{default}/":
        type: redirect
        to: "https://{default}/"
```

In this example, a push would fail because:

- `drupalb` is not an application that is defined that can be used in `routes`
- `bar` is not a service that is defined that can be used in `relationships`

The tests don't currently catch these cases.
